---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: agency
  namespace: argocd
spec:
  description: Agency 1
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
