apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-test-proj
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: Agencies/Agency-1
    repoURL: 'https://github.com/fedorovra/argocd-test-proj.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true