apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-11
  namespace: test
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: Agencies/Agency-1/app-1
    repoURL: https://github.com/fedorovra/argocd-test-proj.git
    targetRevision: HEAD