---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: Agency-1
  namespace: argocd
spec:
  generators:
    git:
      repoURL: https://demo-mars.gitlab.yandexcloud.net/agency/deploy-stage-prod.git
      revision: HEAD
      files:
        - path: "Agencies/Agency-1/App-1/app.yml"
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: Agencies/Agency-1/App-1
    repoURL: 'https://github.com/fedorovra/argocd-test-proj.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true