---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: prod-app-1
    app.kubernetes.io/instance: prod-app-1
spec:
  destination:
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: "./test/"
    repoURL: 'https://github.com/fedorovra/argocd-test-proj.git'
    targetRevision: HEAD
  project: agency
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true