---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-1-stage
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/fedorovra/argocd-test-proj.git
      revision: HEAD
      files:
        - path: "./environments/stage/app/config.yml"
  goTemplate: true
  template:
    metadata:
      name: stage
    spec:
      project: agency
      sources:
        - repoURL: https://github.com/fedorovra/argocd-test-proj.git
          targetRevision: HEAD
          ref: values
          path: "./environments/"
        - repoURL: https://github.com/fedorovra/argocd-test-proj.git
          targetRevision: '{{ .chart.version }}'
          path: "./test-chart/"
          helm:
            releaseName: stage
            valueFiles:
              - $values/stage/{{ .path.basename }}/values.yml
      destination:
        server: https://kubernetes.default.svc
        namespace: stage
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - Validate=true
          - RespectIgnoreDifferences=true
          - Prune=true
