metadata:
  name: app-1
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    path: "./test/"
    repoURL: 'https://github.com/fedorovra/argocd-test-proj.git'
    targetRevision: HEAD
  project: agency