---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agencies
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: "./Agencies"
    repoURL: 'https://github.com/fedorovra/argocd-test-proj.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
